language: ruby
rvm:
  - 2.6.1
install:
  - bundle install
  - npm install
deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  local_dir: _site
  target_branch: master
  on:
    branch: source
